//import "tp_models_events";
//import "tp_views_templates";
//import "exemple_menu";
//import "tp_collections";
//import "tp_rest.js";
//import "tp_game.js";
import "../data/key"
import "graph.js";
import "random.js";